.TH "deprecated" 3 "Sun Jan 19 2025 22:56:40" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
.PP


.PP
.IP "\fBGlobal \fBft_draw_circle\fP (void *mlx_ptr, void *win_ptr, t_circle element)
.IP "" 1c
Not used in the project\&. 

.PP
.IP "\fBGlobal \fBft_draw_rectangle\fP (void *mlx_ptr, void *win_ptr, t_rectangle element)
.IP "" 1c
Not used in the project\&. 

.PP
.IP "\fBFile \fBft_settings\&.c\fP 
.IP "" 1c
This file is deprecated\&. 

.PP

