.TH "inc/ft_keys.h" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/ft_keys.h \- Header file for the key used in so_long\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'X\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKEY_A\fP   97"
.br
.RI "Keycode for the A key\&. "
.ti -1c
.RI "#define \fBKEY_DOWN\fP   65364"
.br
.RI "Keycode for the down key\&. "
.ti -1c
.RI "#define \fBKEY_ENTER\fP   65293"
.br
.RI "Keycode for the enter key\&. "
.ti -1c
.RI "#define \fBKEY_ESCAPE\fP   65307"
.br
.RI "Keycode for the escape key\&. "
.ti -1c
.RI "#define \fBKEY_LEFT\fP   65361"
.br
.RI "Keycode for the left key\&. "
.ti -1c
.RI "#define \fBKEY_RIGHT\fP   65363"
.br
.RI "Keycode for the right key\&. "
.ti -1c
.RI "#define \fBKEY_SPACE\fP   32"
.br
.RI "Keycode for the space key\&. "
.ti -1c
.RI "#define \fBKEY_UP\fP   65362"
.br
.RI "Keycode for the up key\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for the key used in so_long\&. 


.PP
Definition in file \fBft_keys\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
