.TH "C:/Users/Pierre/Documents/Git_Repos/So_long/src/ft_settings.c" 3 "Sun Jan 19 2025 22:56:40" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Pierre/Documents/Git_Repos/So_long/src/ft_settings.c \- Functions related to the settings window\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'keys\&.h'\fP
.br
\fR#include 'mlx\&.h'\fP
.br
\fR#include 'so_long\&.h'\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include 'ft_print\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBft_draw_all_circle\fP (void *mlx_ptr, void *win_settings_ptr)"
.br
.ti -1c
.RI "void * \fBft_settings\fP (\fBt_mlx\fP *mlx)"
.br
.ti -1c
.RI "static int \fBhandle_keypress_settings\fP (int keycode, void *param)"
.br
.ti -1c
.RI "int \fBhandle_mouse_motion_settings\fP (int x, int y, void *param)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions related to the settings window\&. 


.PP
\fBDeprecated\fP
.RS 4
This file is deprecated\&. 
.RE
.PP

.PP
Definition in file \fBft_settings\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "static void ft_draw_all_circle (void * mlx_ptr, void * win_settings_ptr)\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBft_settings\&.c\fP\&.
.SS "void * ft_settings (\fBt_mlx\fP * mlx)"

.PP
Definition at line \fB79\fP of file \fBft_settings\&.c\fP\&.
.SS "static int handle_keypress_settings (int keycode, void * param)\fR [static]\fP"

.PP
Definition at line \fB70\fP of file \fBft_settings\&.c\fP\&.
.SS "int handle_mouse_motion_settings (int x, int y, void * param)"

.PP
Definition at line \fB43\fP of file \fBft_settings\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
