.TH "inc/ft_textures.h" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/ft_textures.h \- Header file for the textures used in so_long\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTEXTURE_COLLECTIBLE\fP   'img/eye_of_ender\&.xpm'"
.br
.ti -1c
.RI "#define \fBTEXTURE_EXIT_OFF\fP   'img/end_portal_off\&.xpm'"
.br
.ti -1c
.RI "#define \fBTEXTURE_EXIT_OFF_FL\fP   'img/player_fl_end_portal_off\&.xpm'"
.br
.ti -1c
.RI "#define \fBTEXTURE_EXIT_OFF_FR\fP   'img/player_fr_end_portal_off\&.xpm'"
.br
.ti -1c
.RI "#define \fBTEXTURE_EXIT_ON\fP   'img/end_portal_on\&.xpm'"
.br
.ti -1c
.RI "#define \fBTEXTURE_FLOOR\fP   'img/parquet_versailles\&.xpm'"
.br
.ti -1c
.RI "#define \fBTEXTURE_PLAYER_FL\fP   'img/player_fl\&.xpm'"
.br
.ti -1c
.RI "#define \fBTEXTURE_PLAYER_FR\fP   'img/player_fr\&.xpm'"
.br
.ti -1c
.RI "#define \fBTEXTURE_WALL\fP   'img/stone_bricks_v2\&.xpm'"
.br
.ti -1c
.RI "#define \fBTEXTURES_EXT\fP   '\&.xpm'"
.br
.ti -1c
.RI "#define \fBTEXTURES_PATH\fP   'img/'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file for the textures used in so_long\&. 


.PP
Definition in file \fBft_textures\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define TEXTURE_COLLECTIBLE   'img/eye_of_ender\&.xpm'"

.PP
Definition at line \fB27\fP of file \fBft_textures\&.h\fP\&.
.SS "#define TEXTURE_EXIT_OFF   'img/end_portal_off\&.xpm'"

.PP
Definition at line \fB32\fP of file \fBft_textures\&.h\fP\&.
.SS "#define TEXTURE_EXIT_OFF_FL   'img/player_fl_end_portal_off\&.xpm'"

.PP
Definition at line \fB31\fP of file \fBft_textures\&.h\fP\&.
.SS "#define TEXTURE_EXIT_OFF_FR   'img/player_fr_end_portal_off\&.xpm'"

.PP
Definition at line \fB30\fP of file \fBft_textures\&.h\fP\&.
.SS "#define TEXTURE_EXIT_ON   'img/end_portal_on\&.xpm'"

.PP
Definition at line \fB33\fP of file \fBft_textures\&.h\fP\&.
.SS "#define TEXTURE_FLOOR   'img/parquet_versailles\&.xpm'"

.PP
Definition at line \fB26\fP of file \fBft_textures\&.h\fP\&.
.SS "#define TEXTURE_PLAYER_FL   'img/player_fl\&.xpm'"

.PP
Definition at line \fB29\fP of file \fBft_textures\&.h\fP\&.
.SS "#define TEXTURE_PLAYER_FR   'img/player_fr\&.xpm'"

.PP
Definition at line \fB28\fP of file \fBft_textures\&.h\fP\&.
.SS "#define TEXTURE_WALL   'img/stone_bricks_v2\&.xpm'"

.PP
Definition at line \fB25\fP of file \fBft_textures\&.h\fP\&.
.SS "#define TEXTURES_EXT   '\&.xpm'"

.PP
Definition at line \fB23\fP of file \fBft_textures\&.h\fP\&.
.SS "#define TEXTURES_PATH   'img/'"

.PP
Definition at line \fB22\fP of file \fBft_textures\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
