.TH "Keys" 3 "Sun Jan 19 2025 22:56:40" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Keys \- Keys macros
.PP
 \- Core functionality of the program\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKEY_A\fP   97"
.br
.ti -1c
.RI "#define \fBKEY_DOWN\fP   65364"
.br
.ti -1c
.RI "#define \fBKEY_ENTER\fP   65293"
.br
.ti -1c
.RI "#define \fBKEY_ESCAPE\fP   65307"
.br
.ti -1c
.RI "#define \fBKEY_LEFT\fP   65361"
.br
.ti -1c
.RI "#define \fBKEY_RIGHT\fP   65363"
.br
.ti -1c
.RI "#define \fBKEY_SPACE\fP   32"
.br
.ti -1c
.RI "#define \fBKEY_UP\fP   65362"
.br
.in -1c
.SH "Detailed Description"
.PP 
Core functionality of the program\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define KEY_A   97"

.PP
Definition at line \fB39\fP of file \fBkeys\&.h\fP\&.
.SS "#define KEY_DOWN   65364"

.PP
Definition at line \fB37\fP of file \fBkeys\&.h\fP\&.
.SS "#define KEY_ENTER   65293"

.PP
Definition at line \fB31\fP of file \fBkeys\&.h\fP\&.
.SS "#define KEY_ESCAPE   65307"

.PP
Definition at line \fB30\fP of file \fBkeys\&.h\fP\&.
.SS "#define KEY_LEFT   65361"

.PP
Definition at line \fB34\fP of file \fBkeys\&.h\fP\&.
.SS "#define KEY_RIGHT   65363"

.PP
Definition at line \fB36\fP of file \fBkeys\&.h\fP\&.
.SS "#define KEY_SPACE   32"

.PP
Definition at line \fB33\fP of file \fBkeys\&.h\fP\&.
.SS "#define KEY_UP   65362"

.PP
Definition at line \fB35\fP of file \fBkeys\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
