.TH "Keys" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Keys \- Keys macros
.PP
 \- Regroup all the keys used in the project\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKEY_A\fP   97"
.br
.RI "Keycode for the A key\&. "
.ti -1c
.RI "#define \fBKEY_DOWN\fP   65364"
.br
.RI "Keycode for the down key\&. "
.ti -1c
.RI "#define \fBKEY_ENTER\fP   65293"
.br
.RI "Keycode for the enter key\&. "
.ti -1c
.RI "#define \fBKEY_ESCAPE\fP   65307"
.br
.RI "Keycode for the escape key\&. "
.ti -1c
.RI "#define \fBKEY_LEFT\fP   65361"
.br
.RI "Keycode for the left key\&. "
.ti -1c
.RI "#define \fBKEY_RIGHT\fP   65363"
.br
.RI "Keycode for the right key\&. "
.ti -1c
.RI "#define \fBKEY_SPACE\fP   32"
.br
.RI "Keycode for the space key\&. "
.ti -1c
.RI "#define \fBKEY_UP\fP   65362"
.br
.RI "Keycode for the up key\&. "
.in -1c
.SH "Detailed Description"
.PP 
Regroup all the keys used in the project\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define KEY_A   97"

.PP
Keycode for the A key\&. 
.PP
Definition at line \fB61\fP of file \fBft_keys\&.h\fP\&.
.SS "#define KEY_DOWN   65364"

.PP
Keycode for the down key\&. 
.PP
Definition at line \fB57\fP of file \fBft_keys\&.h\fP\&.
.SS "#define KEY_ENTER   65293"

.PP
Keycode for the enter key\&. 
.PP
Definition at line \fB37\fP of file \fBft_keys\&.h\fP\&.
.SS "#define KEY_ESCAPE   65307"

.PP
Keycode for the escape key\&. 
.PP
Definition at line \fB33\fP of file \fBft_keys\&.h\fP\&.
.SS "#define KEY_LEFT   65361"

.PP
Keycode for the left key\&. 
.PP
Definition at line \fB45\fP of file \fBft_keys\&.h\fP\&.
.SS "#define KEY_RIGHT   65363"

.PP
Keycode for the right key\&. 
.PP
Definition at line \fB53\fP of file \fBft_keys\&.h\fP\&.
.SS "#define KEY_SPACE   32"

.PP
Keycode for the space key\&. 
.PP
Definition at line \fB41\fP of file \fBft_keys\&.h\fP\&.
.SS "#define KEY_UP   65362"

.PP
Keycode for the up key\&. 
.PP
Definition at line \fB49\fP of file \fBft_keys\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
