.TH "Main" 3 "Sun Jan 19 2025 22:56:40" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main \- Main Functions
.PP
 \- Core functionality of the program\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs_coordinates\fP"
.br
.ti -1c
.RI "struct \fBs_img\fP"
.br
.ti -1c
.RI "struct \fBs_map\fP"
.br
.ti -1c
.RI "struct \fBs_mlx\fP"
.br
.ti -1c
.RI "struct \fBs_store\fP"
.br
.ti -1c
.RI "struct \fBs_textures\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBs_coordinates\fP \fBt_coordinates\fP"
.br
.ti -1c
.RI "typedef struct \fBs_img\fP \fBt_img\fP"
.br
.ti -1c
.RI "typedef struct \fBs_map\fP \fBt_map\fP"
.br
.ti -1c
.RI "typedef struct \fBs_mlx\fP \fBt_mlx\fP"
.br
.ti -1c
.RI "typedef struct \fBs_store\fP \fBt_store\fP"
.br
.ti -1c
.RI "typedef struct \fBs_textures\fP \fBt_textures\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfree_map_textures\fP (\fBt_mlx\fP *mlx, \fBt_map\fP *map)"
.br
.RI "Free the textures from the map\&. "
.ti -1c
.RI "void \fBft_exit\fP (\fBt_mlx\fP mlx, \fBt_map\fP *map)"
.br
.RI "Exit the program\&. "
.ti -1c
.RI "int \fBso_long\fP (int argc, char **argv)"
.br
.RI "Entry point of the program\&. "
.in -1c
.SH "Detailed Description"
.PP 
Core functionality of the program\&. 


.SH "Function Documentation"
.PP 
.SS "void free_map_textures (\fBt_mlx\fP * mlx, \fBt_map\fP * map)"

.PP
Free the textures from the map\&. 
.PP
\fBParameters\fP
.RS 4
\fImlx\fP Pointer to the mlx structure\&. 
.br
\fImap\fP Pointer to the map structure\&. 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBft_free\&.c\fP\&.
.SS "void ft_exit (\fBt_mlx\fP mlx, \fBt_map\fP * map)"

.PP
Exit the program\&. 
.PP
\fBParameters\fP
.RS 4
\fImlx\fP Pointer to the mlx structure\&. 
.br
\fImap\fP Pointer to the map structure\&. 
.RE
.PP

.PP
Definition at line \fB17\fP of file \fBft_exit\&.c\fP\&.
.SS "int so_long (int argc, char ** argv)"

.PP
Entry point of the program\&. 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP Argument count\&. 
.br
\fIargv\fP Argument vector\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int 0 on success, -1 on failure\&.
.RE
.PP
Entry point of the program\&.

.PP
\fBParameters\fP
.RS 4
\fIargc\fP number of arguments 
.br
\fIargv\fP array of string arguments 
.RE
.PP
\fBReturns\fP
.RS 4
int 0 if the program ends correctly, -1 otherwise 
.RE
.PP

.PP
Definition at line \fB28\fP of file \fBso_long\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
