.TH "Player" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player \- Player functions
.PP
 \- All the functions used to make the player playable\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcan_player_move\fP (\fBt_mlx\fP *mlx, \fBt_map\fP *map, int direction)"
.br
.RI "Check if the player can move in the given direction\&. "
.in -1c
.SH "Detailed Description"
.PP 
All the functions used to make the player playable\&. 


.SH "Function Documentation"
.PP 
.SS "void can_player_move (\fBt_mlx\fP * mlx, \fBt_map\fP * map, int direction)"

.PP
Check if the player can move in the given direction\&. 
.PP
\fBParameters\fP
.RS 4
\fImap\fP Pointer to the map structure\&. 
.br
\fImlx\fP Pointer to the mlx structure\&. 
.br
\fIdirection\fP Direction to move (UP, DOWN, LEFT OR RIGHT)\&. 
.RE
.PP

.PP
Definition at line \fB30\fP of file \fBft_player\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
