.TH "Random" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Random \- Random functions
.PP
 \- All the functions used to generate random numbers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_random\fP (int fd)"
.br
.RI "Generate a random int number\&. "
.ti -1c
.RI "int \fBft_random_init\fP (void)"
.br
.RI "Initialize the random function (generates the seed from a random source)\&. "
.in -1c
.SH "Detailed Description"
.PP 
All the functions used to generate random numbers\&. 


.SH "Function Documentation"
.PP 
.SS "int ft_random (int fd)"

.PP
Generate a random int number\&. 
.PP
\fBReturns\fP
.RS 4
int Random number\&. 
.RE
.PP

.PP
Definition at line \fB29\fP of file \fBft_random\&.c\fP\&.
.SS "int ft_random_init (void )"

.PP
Initialize the random function (generates the seed from a random source)\&. 
.PP
\fBReturns\fP
.RS 4
int 0 on success, -1 on failure\&. 
.RE
.PP

.PP
Definition at line \fB19\fP of file \fBft_random\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
