.TH "s_circle" 3 "Sun Jan 19 2025 22:56:40" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_circle
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcolor\fP"
.br
.ti -1c
.RI "int \fBradius\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB125\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int color"

.PP
Definition at line \fB130\fP of file \fBso_long\&.h\fP\&.
.SS "int radius"

.PP
Definition at line \fB129\fP of file \fBso_long\&.h\fP\&.
.SS "int x"

.PP
Definition at line \fB127\fP of file \fBso_long\&.h\fP\&.
.SS "int y"

.PP
Definition at line \fB128\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
