.TH "s_coordinates" 3 "Sun Jan 19 2025 22:56:40" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_coordinates
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBx\fP"
.br
.ti -1c
.RI "size_t \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB60\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "size_t x"

.PP
Definition at line \fB62\fP of file \fBso_long\&.h\fP\&.
.SS "size_t y"

.PP
Definition at line \fB63\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
