.TH "s_coordinates" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_coordinates \- Structure used to store the coordinates (positive only)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <so_long\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBx\fP"
.br
.ti -1c
.RI "size_t \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure used to store the coordinates (positive only)\&. 
.PP
Definition at line \fB76\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "size_t x"

.PP
Definition at line \fB78\fP of file \fBso_long\&.h\fP\&.
.SS "size_t y"

.PP
Definition at line \fB79\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
