.TH "s_img" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_img \- Structure used to store an image (buffer that contain image, and size)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <so_long\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "void * \fBptr\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure used to store an image (buffer that contain image, and size)\&. 
.PP
Definition at line \fB37\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int height"

.PP
Definition at line \fB41\fP of file \fBso_long\&.h\fP\&.
.SS "void* ptr"

.PP
Definition at line \fB39\fP of file \fBso_long\&.h\fP\&.
.SS "int width"

.PP
Definition at line \fB40\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
