.TH "s_map" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_map \- Structure that handle the map informations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <so_long\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcollectibles\fP"
.br
.ti -1c
.RI "int \fBerror\fP"
.br
.ti -1c
.RI "\fBt_coordinates\fP \fBexit\fP"
.br
.ti -1c
.RI "size_t \fBheight\fP"
.br
.ti -1c
.RI "char ** \fBmap\fP"
.br
.ti -1c
.RI "size_t \fBnumber_of_moves\fP"
.br
.ti -1c
.RI "\fBt_textures\fP \fBtextures\fP"
.br
.ti -1c
.RI "size_t \fBwidth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that handle the map informations\&. 
.PP
Definition at line \fB86\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int collectibles"

.PP
Definition at line \fB91\fP of file \fBso_long\&.h\fP\&.
.SS "int error"

.PP
Definition at line \fB89\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_coordinates\fP exit"

.PP
Definition at line \fB92\fP of file \fBso_long\&.h\fP\&.
.SS "size_t height"

.PP
Definition at line \fB94\fP of file \fBso_long\&.h\fP\&.
.SS "char** map"

.PP
Definition at line \fB88\fP of file \fBso_long\&.h\fP\&.
.SS "size_t number_of_moves"

.PP
Definition at line \fB90\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_textures\fP textures"

.PP
Definition at line \fB95\fP of file \fBso_long\&.h\fP\&.
.SS "size_t width"

.PP
Definition at line \fB93\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
