.TH "s_map_size" 3 "Sun Jan 19 2025 22:56:40" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_map_size
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBcount_line\fP"
.br
.ti -1c
.RI "int \fBerror_occured\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "size_t \fBline_len\fP"
.br
.ti -1c
.RI "char * \fBmap_name\fP"
.br
.ti -1c
.RI "size_t \fBprev_line_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB239\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "size_t count_line"

.PP
Definition at line \fB245\fP of file \fBso_long\&.h\fP\&.
.SS "int error_occured"

.PP
Definition at line \fB246\fP of file \fBso_long\&.h\fP\&.
.SS "int fd"

.PP
Definition at line \fB241\fP of file \fBso_long\&.h\fP\&.
.SS "size_t line_len"

.PP
Definition at line \fB243\fP of file \fBso_long\&.h\fP\&.
.SS "char* map_name"

.PP
Definition at line \fB242\fP of file \fBso_long\&.h\fP\&.
.SS "size_t prev_line_len"

.PP
Definition at line \fB244\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
