.TH "s_map" 3 "Sun Jan 19 2025 22:56:40" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_map
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcollectibles\fP"
.br
.ti -1c
.RI "int \fBerror\fP"
.br
.ti -1c
.RI "\fBt_coordinates\fP \fBexit\fP"
.br
.ti -1c
.RI "size_t \fBheight\fP"
.br
.ti -1c
.RI "char ** \fBmap\fP"
.br
.ti -1c
.RI "size_t \fBnumber_of_moves\fP"
.br
.ti -1c
.RI "\fBt_textures\fP \fBtextures\fP"
.br
.ti -1c
.RI "size_t \fBwidth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB66\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int collectibles"

.PP
Definition at line \fB71\fP of file \fBso_long\&.h\fP\&.
.SS "int error"

.PP
Definition at line \fB69\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_coordinates\fP exit"

.PP
Definition at line \fB72\fP of file \fBso_long\&.h\fP\&.
.SS "size_t height"

.PP
Definition at line \fB74\fP of file \fBso_long\&.h\fP\&.
.SS "char** map"

.PP
Definition at line \fB68\fP of file \fBso_long\&.h\fP\&.
.SS "size_t number_of_moves"

.PP
Definition at line \fB70\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_textures\fP textures"

.PP
Definition at line \fB75\fP of file \fBso_long\&.h\fP\&.
.SS "size_t width"

.PP
Definition at line \fB73\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
