.TH "s_map_size" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_map_size \- Structure used to store the map dimensions and metadata\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <so_long\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBcount_line\fP"
.br
.ti -1c
.RI "int \fBerror_occured\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "size_t \fBline_len\fP"
.br
.ti -1c
.RI "char * \fBmap_name\fP"
.br
.ti -1c
.RI "size_t \fBprev_line_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure used to store the map dimensions and metadata\&. 
.PP
Definition at line \fB276\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "size_t count_line"

.PP
Definition at line \fB282\fP of file \fBso_long\&.h\fP\&.
.SS "int error_occured"

.PP
Definition at line \fB283\fP of file \fBso_long\&.h\fP\&.
.SS "int fd"

.PP
Definition at line \fB278\fP of file \fBso_long\&.h\fP\&.
.SS "size_t line_len"

.PP
Definition at line \fB280\fP of file \fBso_long\&.h\fP\&.
.SS "char* map_name"

.PP
Definition at line \fB279\fP of file \fBso_long\&.h\fP\&.
.SS "size_t prev_line_len"

.PP
Definition at line \fB281\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
