.TH "s_mlx" 3 "Sun Jan 19 2025 22:56:40" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_mlx
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBmlx_ptr\fP"
.br
.ti -1c
.RI "void * \fBwin_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB53\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "void* mlx_ptr"

.PP
Definition at line \fB55\fP of file \fBso_long\&.h\fP\&.
.SS "void* win_ptr"

.PP
Definition at line \fB56\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
