.TH "s_mlx" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_mlx \- Structure that handle the mlx instance\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <so_long\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBmlx_ptr\fP"
.br
.ti -1c
.RI "void * \fBwin_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure that handle the mlx instance\&. 
.PP
Definition at line \fB65\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "void* mlx_ptr"

.PP
Definition at line \fB67\fP of file \fBso_long\&.h\fP\&.
.SS "void* win_ptr"

.PP
Definition at line \fB68\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
