.TH "s_rectangle" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_rectangle \- Structure used to draw a rectangle\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <so_long\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcolor\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure used to draw a rectangle\&. 
.PP
Definition at line \fB144\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int color"

.PP
Definition at line \fB150\fP of file \fBso_long\&.h\fP\&.
.SS "int height"

.PP
Definition at line \fB149\fP of file \fBso_long\&.h\fP\&.
.SS "int width"

.PP
Definition at line \fB148\fP of file \fBso_long\&.h\fP\&.
.SS "int x"

.PP
Definition at line \fB146\fP of file \fBso_long\&.h\fP\&.
.SS "int y"

.PP
Definition at line \fB147\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
