.TH "s_store" 3 "Sun Jan 19 2025 22:56:40" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_store
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_map\fP * \fBmap\fP"
.br
.ti -1c
.RI "\fBt_mlx\fP * \fBmlx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB78\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBt_map\fP* map"

.PP
Definition at line \fB81\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_mlx\fP* mlx"

.PP
Definition at line \fB80\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
