.TH "s_store" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_store \- Structure used to store the mlx and map structures\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <so_long\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_map\fP * \fBmap\fP"
.br
.ti -1c
.RI "\fBt_mlx\fP * \fBmlx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure used to store the mlx and map structures\&. 
.PP
Definition at line \fB102\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBt_map\fP* map"

.PP
Definition at line \fB105\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_mlx\fP* mlx"

.PP
Definition at line \fB104\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
