.TH "s_textures" 3 "Sun Jan 19 2025 22:56:40" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_textures
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_img\fP \fBcollectible\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBexit_off\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBexit_off_fl\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBexit_off_fr\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBexit_on\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBfloor\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBplayer_fl\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBplayer_fr\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBwall\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB40\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBt_img\fP collectible"

.PP
Definition at line \fB50\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP exit_off"

.PP
Definition at line \fB43\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP exit_off_fl"

.PP
Definition at line \fB45\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP exit_off_fr"

.PP
Definition at line \fB44\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP exit_on"

.PP
Definition at line \fB46\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP floor"

.PP
Definition at line \fB47\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP player_fl"

.PP
Definition at line \fB49\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP player_fr"

.PP
Definition at line \fB48\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP wall"

.PP
Definition at line \fB42\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
