.TH "s_textures" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_textures \- Strcuture that handle the textures of the game\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <so_long\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_img\fP \fBcollectible\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBexit_off\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBexit_off_fl\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBexit_off_fr\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBexit_on\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBfloor\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBplayer_fl\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBplayer_fr\fP"
.br
.ti -1c
.RI "\fBt_img\fP \fBwall\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Strcuture that handle the textures of the game\&. 
.PP
Definition at line \fB48\fP of file \fBso_long\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBt_img\fP collectible"

.PP
Definition at line \fB58\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP exit_off"

.PP
Definition at line \fB51\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP exit_off_fl"

.PP
Definition at line \fB53\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP exit_off_fr"

.PP
Definition at line \fB52\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP exit_on"

.PP
Definition at line \fB54\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP floor"

.PP
Definition at line \fB55\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP player_fl"

.PP
Definition at line \fB57\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP player_fr"

.PP
Definition at line \fB56\fP of file \fBso_long\&.h\fP\&.
.SS "\fBt_img\fP wall"

.PP
Definition at line \fB50\fP of file \fBso_long\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
