.TH "Utils" 3 "Sun Feb 16 2025 11:49:25" "So_long" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils \- Utils functions
.PP
 \- All the functions used to help the program\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBfind_max_collectibles\fP (\fBt_map\fP *map)"
.br
.RI "Find the maximum number of collectibles in the map\&. "
.ti -1c
.RI "\fBt_coordinates\fP \fBfind_position\fP (\fBt_map\fP *map, char character)"
.br
.RI "Find the position of a character in the map\&. "
.ti -1c
.RI "char * \fBft_strdup\fP (const char *source)"
.br
.RI "Create a copy of source into a new pointer NEEDS to be freed\&. "
.in -1c
.SH "Detailed Description"
.PP 
All the functions used to help the program\&. 


.SH "Function Documentation"
.PP 
.SS "int find_max_collectibles (\fBt_map\fP * map)"

.PP
Find the maximum number of collectibles in the map\&. 
.PP
\fBParameters\fP
.RS 4
\fImap\fP Pointer to the map structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
int Number of collectibles\&. 
.RE
.PP

.PP
Definition at line \fB17\fP of file \fBft_map_utils\&.c\fP\&.
.SS "\fBt_coordinates\fP find_position (\fBt_map\fP * map, char character)"

.PP
Find the position of a character in the map\&. 
.PP
\fBParameters\fP
.RS 4
\fImap\fP Pointer to the map structure\&. 
.br
\fIcharacter\fP character to find\&. 
.RE
.PP
\fBReturns\fP
.RS 4
\fBt_coordinates\fP coordinates of the character\&. 
.RE
.PP

.PP
Definition at line \fB39\fP of file \fBft_map_utils\&.c\fP\&.
.SS "char * ft_strdup (const char * source)"

.PP
Create a copy of source into a new pointer NEEDS to be freed\&. 
.PP
\fBParameters\fP
.RS 4
\fIsource\fP Source string\&. 
.RE
.PP
\fBReturns\fP
.RS 4
char* Pointer to the new string\&. 
.RE
.PP

.PP
Definition at line \fB16\fP of file \fBft_strdup\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for So_long from the source code\&.
